variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_DEV
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_DEV
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: "354156725301"         
  ECR_NAME: "ds-repo-docker-custom-image"
  TERRAFORM_VERSION: "1.5.7"
  PY_VERSIONS: "3.11 3.12 3.13 3.14"
  DOCKER_BUILDKIT: "1"

default:
  image:
    name: docker:27.3.1-cli
    entrypoint: [""]

stages:
  - build

build_and_push:
  stage: build
  #image: docker:24.0.2
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache bash curl jq python3 py3-pip git
    - pip3 install --no-cache-dir awscli
    - export AWS_REGION=${AWS_REGION}
    - echo "Logging into ECR ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    - aws --version
    - aws ecr describe-repositories --repository-names "${ECR_NAME}" --region "${AWS_REGION}" || aws ecr create-repository --repository-name "${ECR_NAME}" --region "${AWS_REGION}"
    - aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
  script: |
    set -euo pipefail
    export DOCKER_BUILDKIT=${DOCKER_BUILDKIT:-1}
    mkdir -p e2-${ECR_NAME}
    cd e2-${ECR_NAME} || exit 1
    cp ../Dockerfile.multi .
    echo "Building versions: ${PY_VERSIONS}"
    for VERSION in ${PY_VERSIONS}; do
      TAG="py${VERSION//./}"
      echo "Building ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_NAME}:${TAG} (Python ${VERSION})"
      docker build --pull --build-arg PYTHON_VERSION="${VERSION}" --build-arg TERRAFORM_VERSION="${TERRAFORM_VERSION}" -t "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_NAME}:${TAG}" -f Dockerfile.multi ..
      echo "Smoke test (python --version)..."
      docker run --rm "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_NAME}:${TAG}" python --version || true
      docker push "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_NAME}:${TAG}"
      echo "✓ Built and pushed ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_NAME}:${TAG}"
    done
  only:
    - main
