USE ROLE SPCS_STREAMLIT_APP_ROLE;
USE DATABASE POC_SPCS_DB;
USE SCHEMA POC_SPCS_SCHEMA;

SHOW SERVICES LIKE 'POC_STREAMLIT_SERVICE';
SELECT
  "name",
  "status",
  "dns_name"
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW SERVICE INSTANCES IN SERVICE POC_STREAMLIT_SERVICE;
SELECT
  "instance_id",
  "status",
  "start_time"
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW SERVICE CONTAINERS IN SERVICE POC_STREAMLIT_SERVICE;
SELECT
  "instance_id",
  "container_name",
  "status",
  "message"
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

SHOW ENDPOINTS IN SERVICE POC_STREAMLIT_SERVICE;
SELECT
  "name",
  "port",
  "is_public",
  "ingress_url"
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
