-- Setup users + role + row-level security demo table for Streamlit app
-- Execute as ACCOUNTADMIN.

USE ROLE ACCOUNTADMIN;
USE DATABASE POC_SPCS_DB;
USE SCHEMA POC_SPCS_SCHEMA;

CREATE ROLE IF NOT EXISTS SPCS_DEMO_RLS_ROLE;

-- Assign role to your admin user so you can test quickly
GRANT ROLE SPCS_DEMO_RLS_ROLE TO USER JOHNPOC022026;

-- Demo users with password login (replace passwords in production)
CREATE USER IF NOT EXISTS SPCS_DEMO_TIM
  PASSWORD = 'Tim#2026!'
  DEFAULT_ROLE = SPCS_DEMO_RLS_ROLE
  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER IF NOT EXISTS SPCS_DEMO_BRUNO
  PASSWORD = 'Bruno#2026!'
  DEFAULT_ROLE = SPCS_DEMO_RLS_ROLE
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE SPCS_DEMO_RLS_ROLE TO USER SPCS_DEMO_TIM;
GRANT ROLE SPCS_DEMO_RLS_ROLE TO USER SPCS_DEMO_BRUNO;

-- Warehouse access (adjust warehouse name if needed)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SPCS_DEMO_RLS_ROLE;

-- Database and schema access
GRANT USAGE ON DATABASE POC_SPCS_DB TO ROLE SPCS_DEMO_RLS_ROLE;
GRANT USAGE ON SCHEMA POC_SPCS_DB.POC_SPCS_SCHEMA TO ROLE SPCS_DEMO_RLS_ROLE;

-- Demo fact table
CREATE OR REPLACE TABLE APP_DEMO_ORDERS (
  ORDER_ID NUMBER,
  REGION STRING,
  AMOUNT NUMBER(12,2),
  EVENT_TS TIMESTAMP_NTZ
);

INSERT OVERWRITE INTO APP_DEMO_ORDERS (ORDER_ID, REGION, AMOUNT, EVENT_TS) VALUES
  (1, 'NORTH', 1200, CURRENT_TIMESTAMP()),
  (2, 'NORTH', 980,  DATEADD('hour', -1, CURRENT_TIMESTAMP())),
  (3, 'SOUTH', 450,  DATEADD('hour', -2, CURRENT_TIMESTAMP())),
  (4, 'SOUTH', 760,  DATEADD('hour', -3, CURRENT_TIMESTAMP())),
  (5, 'EAST',  300,  DATEADD('hour', -4, CURRENT_TIMESTAMP())),
  (6, 'WEST',  1500, DATEADD('hour', -5, CURRENT_TIMESTAMP()));

GRANT SELECT ON TABLE APP_DEMO_ORDERS TO ROLE SPCS_DEMO_RLS_ROLE;

-- Mapping table: which Snowflake user can see which region
CREATE OR REPLACE TABLE APP_DEMO_USER_REGION_ACCESS (
  USER_NAME STRING,
  REGION STRING
);

INSERT OVERWRITE INTO APP_DEMO_USER_REGION_ACCESS (USER_NAME, REGION) VALUES
  ('SPCS_DEMO_TIM', 'NORTH'),
  ('SPCS_DEMO_TIM', 'EAST'),
  ('SPCS_DEMO_BRUNO', 'SOUTH'),
  ('SPCS_DEMO_BRUNO', 'WEST'),
  ('JOHNPOC022026', 'NORTH'),
  ('JOHNPOC022026', 'SOUTH'),
  ('JOHNPOC022026', 'EAST'),
  ('JOHNPOC022026', 'WEST');

GRANT SELECT ON TABLE APP_DEMO_USER_REGION_ACCESS TO ROLE SPCS_DEMO_RLS_ROLE;

-- Row Access Policy based on CURRENT_USER()
CREATE OR REPLACE ROW ACCESS POLICY APP_DEMO_ORDERS_RLS
AS (REGION STRING) RETURNS BOOLEAN ->
  EXISTS (
    SELECT 1
    FROM APP_DEMO_USER_REGION_ACCESS M
    WHERE UPPER(M.USER_NAME) = UPPER(CURRENT_USER())
      AND UPPER(M.REGION) = UPPER(REGION)
  );

ALTER TABLE APP_DEMO_ORDERS ADD ROW ACCESS POLICY APP_DEMO_ORDERS_RLS ON (REGION);
